  name: webrtc-streamer
  version: git
  summary: webrtc streamer
  description: |
     WebRTC-streamer is an experiment to stream video capture devices and RTSP sources through WebRTC using simple mechanism.

     It embeds a HTTP server that implements API and serves a simple HTML page that use them through AJAX.

     The WebRTC signaling is implemented through HTTP requests:
     * /api/call : send offer and get answer
     * /api/hangup : close a call
     * /api/addIceCandidate : add a candidate
     * /api/getIceCandidate : get the list of candidates

  grade: stable 
  confinement: strict
  base: core22
  architectures:
    - build-on: amd64

  parts:
    webrtc:
      plugin: python
      source: https://chromium.googlesource.com/chromium/tools/depot_tools.git
      source-type: git
      override-build: |
        cp -r ../src/* /usr/local/bin/
        mkdir /webrtc
        cd /webrtc
        fetch --no-history --nohooks webrtc
        sed -i -e "s|'src/resources'],|'src/resources'],'condition':'rtc_include_tests==true',|" src/DEPS
        gclient sync
      build-packages:
      - curl
      - python3
      - python3-httplib2

    webrtc-streamer:
      after: [webrtc]
      plugin: cmake
      source: .
      source-type: git
      cmake-parameters:
      - -DWEBRTCROOT=/webrtc
      build-packages:
      - g++
      - make
      - pkg-config
      - python3 
      - python3-pkg-resources
      - libgtk-3-dev
      - libasound2-dev
      - libpulse-dev
      - libssl-dev
      - librtmp-dev
      stage-packages:
      - libgtk-3-0
      - libasound2
      - libpulse0
      - libssl-dev
      - librtmp1

  apps:
    webrtc-streamer:
      command: webrtc-streamer -C $SNAP/config.json -w $SNAP/html
      daemon: simple   
      plugs: [network-bind]
